// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pvp.Data;

#nullable disable

namespace pvp.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20230222171149_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pvp.Data.Entities.ParinktosUzduotys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Skelbimas_id")
                        .HasColumnType("int");

                    b.Property<int>("Uzduotys_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("parinktosUzduotys");
                });

            modelBuilder.Entity("pvp.Data.Entities.Prisijunge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Skelbimas_id")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Uzduotys_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("prisijunges");
                });

            modelBuilder.Entity("pvp.Data.Entities.Rezultatai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Duomenys")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Pavyzdine")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rezultatas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Uzduotis_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rezultatais");
                });

            modelBuilder.Entity("pvp.Data.Entities.Skelbimas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aprasymas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Pabaiga")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Pradzia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("skelbimas");
                });

            modelBuilder.Entity("pvp.Data.Entities.Sprendimas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CpuIsnaudojimas")
                        .HasColumnType("int");

                    b.Property<int>("ParinktosUzduotys_id")
                        .HasColumnType("int");

                    b.Property<int>("Prisijunge_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Programa")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("ProgramosLaikasSek")
                        .HasColumnType("int");

                    b.Property<int>("ProgramosLaikasTaskai")
                        .HasColumnType("int");

                    b.Property<int>("RamIsnaudojimas")
                        .HasColumnType("int");

                    b.Property<int>("ResursaiTaskai")
                        .HasColumnType("int");

                    b.Property<int>("Teisingumas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("sprendimas");
                });

            modelBuilder.Entity("pvp.Data.Entities.Tipas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aprasymas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tipas");
                });

            modelBuilder.Entity("pvp.Data.Entities.Uzduotys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aprasymas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Mokomoji")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Patvirtinta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sudetingumas")
                        .HasColumnType("int");

                    b.Property<int>("Tipas_id")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("uzduotys");
                });
#pragma warning restore 612, 618
        }
    }
}
